In [1]:
# 셀(cell)에 Python 코드 또는 주석을 입력
# 셀에 입력된 코드를 실행하면 콘솔에 실행 결과를 보여줌(단, 할당일 때는 아무 것도 안 나옴)
print('hello world')

hello world


In [2]:
# shift + enter
# print() 함수는 객체를 출력하면서 None을 반환하므로 Output이 없어요.
# 만약 콘솔에 [n]이 보인다면 그것은 Python 객체가 반환된 것입니다.
1 + 2

3

In [3]:
name = input('당신의 이름은? ')

당신의 이름은?  류현진


In [4]:
name

'류현진'

In [5]:
1 + 3

4

In [6]:
1 + 4

5

In [9]:
import numpy as np

In [14]:
li1 = [1, 2.0, '3']
li1

[1, 2.0, '3']

In [15]:
# np.array() 함수의 object 매개변수에 li1이라는 전달인수를 연결
# 함수: f(x) = ax + b
ar1 = np.array(object = li1)
ar1

array(['1', '2.0', '3'], dtype='<U32')

In [16]:
type(ar1)

numpy.ndarray

In [17]:
ar1.ndim

1

In [18]:
ar1.shape

(3,)

In [19]:
ar1.size

3

In [20]:
ar1.dtype

dtype('<U32')

In [21]:
ar1.astype(int)

ValueError: invalid literal for int() with base 10: np.str_('2.0')

In [22]:
ar1.astype(float)

array([1., 2., 3.])

In [23]:
# method chaining
ar1.astype(float).astype(int)

array([1, 2, 3])

In [24]:
ar1.astype(float).astype(int).astype(str)

array(['1', '2', '3'], dtype='<U21')

In [25]:
np.array(object = li1, dtype = int)

array([1, 2, 3])

In [26]:
np.array(object = li1, dtype = float)

array([1., 2., 3.])

In [27]:
np.array(object = li1, dtype = str)

array(['1', '2.0', '3'], dtype='<U3')

In [28]:
np.array(object = li1, dtype = object)

array([1, 2.0, '3'], dtype=object)

In [30]:
list(range(6))

[0, 1, 2, 3, 4, 5]

In [31]:
list(range(1, 6))

[1, 2, 3, 4, 5]

In [32]:
list(range(1, 6, 2))

[1, 3, 5]

In [33]:
list(range(0, 1, 0.1))

TypeError: 'float' object cannot be interpreted as an integer

In [34]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [35]:
np.arange(1, 6)

array([1, 2, 3, 4, 5])

In [36]:
np.arange(1, 6, 2)

array([1, 3, 5])

In [37]:
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [38]:
np.arange(0, 1.1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [39]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [40]:
np.linspace(80, 75, 30+1)

array([80.        , 79.83333333, 79.66666667, 79.5       , 79.33333333,
       79.16666667, 79.        , 78.83333333, 78.66666667, 78.5       ,
       78.33333333, 78.16666667, 78.        , 77.83333333, 77.66666667,
       77.5       , 77.33333333, 77.16666667, 77.        , 76.83333333,
       76.66666667, 76.5       , 76.33333333, 76.16666667, 76.        ,
       75.83333333, 75.66666667, 75.5       , 75.33333333, 75.16666667,
       75.        ])

In [42]:
# 함수와 메서드의 괄호 안에 커서를 놓고 shift + tab 키를 동시에 누르면
# 해당 함수의 설명서를 확인할 수 있습니다.
np.tile(A = ar1, reps = 2)

array(['1', '2.0', '3', '1', '2.0', '3'], dtype='<U32')

In [43]:
np.repeat(a = ar1, repeats = 2)

array(['1', '1', '2.0', '2.0', '3', '3'], dtype='<U32')

In [44]:
np.repeat(a = ar1, repeats = [3, 2, 1])

array(['1', '1', '1', '2.0', '2.0', '3'], dtype='<U32')

In [45]:
np.repeat(a = ar1, repeats = range(3, 0, -1))

array(['1', '1', '1', '2.0', '2.0', '3'], dtype='<U32')

In [46]:
ar1 = np.arange(1, 12, 2)
ar1

array([ 1,  3,  5,  7,  9, 11])

In [47]:
ar1[0]

np.int64(1)

In [48]:
ar1[1]

np.int64(3)

In [49]:
ar1[-1]

np.int64(11)

In [50]:
ar1[0:3]

array([1, 3, 5])

In [51]:
ar1[:3]

array([1, 3, 5])

In [52]:
ar1[3:]

array([ 7,  9, 11])

In [53]:
ar1[:]

array([ 1,  3,  5,  7,  9, 11])

In [54]:
ar1[[3, 1, 2]]

array([7, 3, 5])

In [55]:
ar1[[3, 3, 3]]

array([7, 7, 7])

In [56]:
ar1[np.tile(A = 3, reps = 3)]

array([7, 7, 7])

In [58]:
[3] * 3

[3, 3, 3]

In [59]:
ar1[[3] * 3]

array([7, 7, 7])

In [60]:
ar1[[False, False, False, True, True, True]]

array([ 7,  9, 11])

In [61]:
ar1[np.repeat(a = [False, True], repeats = 3)]

array([ 7,  9, 11])

In [62]:
ar1

array([ 1,  3,  5,  7,  9, 11])

In [63]:
# 브로드캐스팅
ar1 >= 7

array([False, False, False,  True,  True,  True])

In [64]:
ar1[ar1 >= 7]

array([ 7,  9, 11])

In [65]:
li2 = [[1, 3, 5], [2, 4, 6]]
li2

[[1, 3, 5], [2, 4, 6]]

In [66]:
ar2 = np.array(object = li2)
ar2

array([[1, 3, 5],
       [2, 4, 6]])

In [67]:
type(ar2)

numpy.ndarray

In [68]:
ar2.ndim

2

In [69]:
ar2.shape

(2, 3)

In [70]:
ar2.size

6

In [71]:
ar2.dtype

dtype('int64')

In [72]:
ar2

array([[1, 3, 5],
       [2, 4, 6]])

In [73]:
ar2[0, 0]

np.int64(1)

In [74]:
ar2[0]

array([1, 3, 5])

In [75]:
ar2[0:2, 0:2]

array([[1, 3],
       [2, 4]])

In [76]:
ar2[:, 1:3]

array([[3, 5],
       [4, 6]])

In [77]:
ar2[:, [2, 1]]

array([[5, 3],
       [6, 4]])

In [78]:
ar1

array([ 1,  3,  5,  7,  9, 11])

In [79]:
ar1.reshape(2, 3)

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [80]:
ar1.reshape(2, 3, order = 'F')

array([[ 1,  5,  9],
       [ 3,  7, 11]])

In [81]:
ar2 = ar1.reshape(2, -1)
ar2

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [82]:
ar1.reshape(-1, 3)

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [83]:
ar2.flatten()

array([ 1,  3,  5,  7,  9, 11])

In [84]:
ar2.ravel()

array([ 1,  3,  5,  7,  9, 11])

In [85]:
np.array([0, 1, 2])

array([0, 1, 2])

In [88]:
ar1 = np.array([[0, 1, 2]])
ar1

array([[0, 1, 2]])

In [89]:
ar1 + 1

array([[1, 2, 3]])

In [90]:
[0, 1, 2] + 1

TypeError: can only concatenate list (not "int") to list

In [91]:
ar2 = ar1.reshape(-1, 1)
ar2

array([[0],
       [1],
       [2]])

In [92]:
ar2 * 2

array([[0],
       [2],
       [4]])

In [93]:
ar1 = np.array([1, 4, 9, 16, 25])

In [94]:
np.diff(ar1)

array([3, 5, 7, 9])

In [98]:
ar1 = np.array([3, 6, 4, 2, 5, 1, 4, 8, 1, 6, 8])

In [99]:
np.min(ar1)

np.int64(1)

In [100]:
np.argmin(ar1)

np.int64(5)

In [101]:
np.max(ar1)

np.int64(8)

In [102]:
np.argmax(ar1)

np.int64(7)

In [103]:
np.argsort(ar1)

array([ 5,  8,  3,  0,  6,  2,  4,  1,  9,  7, 10])

In [110]:
# 재현 가능한 결과를 얻고 싶을 때 시드를 설정합니다.
np.random.seed(2)
np.random.rand(2, 3)

array([[0.4359949 , 0.02592623, 0.54966248],
       [0.43532239, 0.4203678 , 0.33033482]])

In [111]:
np.random.seed(2)
np.random.rand(2, 3)

array([[0.4359949 , 0.02592623, 0.54966248],
       [0.43532239, 0.4203678 , 0.33033482]])

In [113]:
np.random.randint(5, size = 10)

array([2, 4, 4, 4, 3, 4, 2, 3, 3, 2], dtype=int32)

In [116]:
lotto = np.random.choice(a = range(1, 46), size = 6, replace = False)
sorted(lotto)

[np.int64(3),
 np.int64(10),
 np.int64(20),
 np.int64(25),
 np.int64(40),
 np.int64(42)]

In [123]:
import pandas as pd

In [124]:
np.random.seed(20250512)
for i in range(10):
    lotto = np.random.choice(a = range(1, 46), size = 6, replace = False)
    lotto = pd.Series(lotto)
    print(sorted(lotto))

[1, 10, 12, 30, 34, 37]
[4, 10, 13, 23, 34, 44]
[17, 20, 21, 26, 28, 30]
[3, 7, 28, 34, 35, 38]
[12, 14, 31, 36, 39, 43]
[3, 14, 23, 25, 28, 38]
[6, 24, 26, 29, 33, 36]
[1, 7, 17, 35, 37, 41]
[4, 6, 15, 26, 36, 42]
[10, 24, 34, 38, 41, 44]


In [131]:
li1 = [1, 2.0, '3']
li1

[1, 2.0, '3']

In [132]:
ar1 = np.array(object = li1)
ar1

array(['1', '2.0', '3'], dtype='<U32')

In [133]:
# 맨 왼쪽은 인덱스, 맨 오른쪽은 밸류스(numpy.ndarray)
# 시리즈의 데이터 타입이 object이면 원소에 문자열이 있다는 것을 의미합니다.
sr = pd.Series(data = li1)
sr

0      1
1    2.0
2      3
dtype: object

In [135]:
type(sr)

pandas.core.series.Series

In [134]:
for i in sr:
    print(type(i))

<class 'int'>
<class 'float'>
<class 'str'>


In [136]:
sr + '1'

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [137]:
sr + 1

TypeError: can only concatenate str (not "int") to str

In [139]:
sr.astype(str) + '1'

0      11
1    2.01
2      31
dtype: object

In [140]:
sr.astype(int) + 1

0    2
1    3
2    4
dtype: int64

In [141]:
sr.astype(float) + 1

0    2.0
1    3.0
2    4.0
dtype: float64

In [143]:
sr.astype(str).astype(int)

ValueError: invalid literal for int() with base 10: '2.0'

In [144]:
sr = sr.astype(float)
sr

0    1.0
1    2.0
2    3.0
dtype: float64

In [145]:
sr.shape

(3,)

In [146]:
sr.size

3

In [147]:
sr.dtype

dtype('float64')

In [148]:
sr.index

RangeIndex(start=0, stop=3, step=1)

In [149]:
sr.values

array([1., 2., 3.])

In [150]:
sr.index = [1, 2, 3]

In [151]:
sr

1    1.0
2    2.0
3    3.0
dtype: float64

In [152]:
sr.index = [1, 1, 1]
sr

1    1.0
1    2.0
1    3.0
dtype: float64

In [153]:
sr.index = [1.0, 2.0, 3.0]
sr

1.0    1.0
2.0    2.0
3.0    3.0
dtype: float64

In [154]:
sr.index = ['a', 'b', 'c']
sr

a    1.0
b    2.0
c    3.0
dtype: float64

In [155]:
pd.Series(data = li1, index = ['a', 'b', 'c'])

a      1
b    2.0
c      3
dtype: object

In [156]:
di1 = {'a': 1, 'b': 2.0, 'c': '3'}
pd.Series(data = di1)

a      1
b    2.0
c      3
dtype: object

In [158]:
sr[sr == 3]

c    3.0
dtype: float64

In [159]:
sr

a    1.0
b    2.0
c    3.0
dtype: float64

In [160]:
sr[0]

C:\Users\USER\AppData\Local\Temp\ipykernel_2108\3717362250.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  sr[0]


np.float64(1.0)

In [161]:
sr.iloc[0]

np.float64(1.0)

In [162]:
sr['a']

np.float64(1.0)

In [163]:
sr.loc['a']

np.float64(1.0)

In [164]:
# 정수 인덱스로 슬라이싱할 때는 끝 인덱스를 포함하지 않습니다.
sr.iloc[0:3]

a    1.0
b    2.0
c    3.0
dtype: float64

In [165]:
# 행이름으로 슬라이싱할 때는 끝 인덱스를 포함합니다.
sr.loc['a':'c']

a    1.0
b    2.0
c    3.0
dtype: float64

In [166]:
sr0 = pd.Series(data = li1, index = ['c', 'a', 'b'])

In [167]:
sr0['a':'c']

Series([], dtype: object)

In [168]:
sr0['c':'a']

c      1
a    2.0
dtype: object

In [169]:
sr

a    1.0
b    2.0
c    3.0
dtype: float64

In [170]:
sr[[0, 2]]

C:\Users\USER\AppData\Local\Temp\ipykernel_2108\1530571964.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  sr[[0, 2]]


a    1.0
c    3.0
dtype: float64

In [171]:
sr[['a', 'c']]

a    1.0
c    3.0
dtype: float64

In [172]:
sr[[True, False, False]]

a    1.0
dtype: float64

In [173]:
sr[sr == 1]

a    1.0
dtype: float64

In [174]:
# 인덱싱은 원소 그 자체로 반환
sr.iloc[0]

np.float64(1.0)

In [175]:
# 슬라이싱은 무조건 시리즈로 반환
sr.iloc[0:3]

a    1.0
b    2.0
c    3.0
dtype: float64

In [176]:
# 배열 인덱싱도 무조건 시리즈로 반환
sr.iloc[[0]]

a    1.0
dtype: float64

In [177]:
# 불리언 인덱싱은 불가
sr.iloc[sr == 1]

ValueError: iLocation based boolean indexing cannot use an indexable as a mask

In [179]:
sr.loc['a']

np.float64(1.0)

In [180]:
sr.loc['a':'c']

a    1.0
b    2.0
c    3.0
dtype: float64

In [181]:
sr.loc[['a']]

a    1.0
dtype: float64

In [182]:
sr.loc[sr == 1]

a    1.0
dtype: float64

In [183]:
sr1 = pd.Series(data = li1, index = range(1, 4))
sr1

1      1
2    2.0
3      3
dtype: object

In [184]:
sr1[0]

KeyError: 0

In [185]:
sr1.iloc[0]

1

In [186]:
sr1.loc[1]

1

In [187]:
sr2 = pd.Series(data = li1, index = [1] * 3)
sr2

1      1
1    2.0
1      3
dtype: object

In [188]:
sr2.loc[1]

1      1
1    2.0
1      3
dtype: object

In [190]:
sr2.iloc[0]

1

In [191]:
sr

a    1.0
b    2.0
c    3.0
dtype: float64

In [193]:
sr.loc['d'] = 4
sr

a    1.0
b    2.0
c    3.0
d    4.0
dtype: float64

In [194]:
sr.loc['d'] = 5
sr

a    1.0
b    2.0
c    3.0
d    5.0
dtype: float64

In [196]:
sr.drop(index = ['a', 'd'])

b    2.0
c    3.0
dtype: float64

In [198]:
sr.loc['e'] = '5'
sr

a    1.0
b    2.0
c    3.0
d    5.0
dtype: float64

In [199]:
sr >= 1

a    True
b    True
c    True
d    True
dtype: bool

In [200]:
# 논리 연산자(and, or, not)은 불리언 스칼라만 사용할 수 있기 때문입니다.
sr >= 1 and sr < 3

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [201]:
for i in sr:
    print(i >= 1 and i < 3)

True
True
False
False


In [203]:
# 논리곱은 교집합
(sr >= 1) & (sr < 3)

a     True
b     True
c    False
d    False
dtype: bool

In [204]:
# 논리합은 합집합
(sr >= 1) | (sr < 3)

a    True
b    True
c    True
d    True
dtype: bool

In [205]:
# 배타적 논리합은 합집합에서 교집합을 뺀 것
(sr >= 1) ^ (sr < 3)

a    False
b    False
c     True
d     True
dtype: bool

In [207]:
# 논리부정은 여집합
~((sr >= 1) & (sr < 3))

a    False
b    False
c     True
d     True
dtype: bool

In [208]:
sr1

1      1
2    2.0
3      3
dtype: object

In [209]:
sr3 = sr1

In [210]:
id(sr1)

2072862595104

In [211]:
id(sr3)

2072862595104

In [212]:
id(sr1) == id(sr3)

True

In [213]:
sr3

1      1
2    2.0
3      3
dtype: object

In [215]:
sr3.iloc[0] = 2

In [216]:
sr3

1      2
2    2.0
3      3
dtype: object

In [217]:
sr1

1      2
2    2.0
3      3
dtype: object

In [218]:
sr4 = sr1.copy()

In [219]:
id(sr1) == id(sr4)

False

In [220]:
sr4

1      2
2    2.0
3      3
dtype: object

In [221]:
sr4.iloc[0] = 1

In [222]:
sr4

1      1
2    2.0
3      3
dtype: object

In [223]:
sr1

1      2
2    2.0
3      3
dtype: object

In [224]:
li2 = [[1, 2], [3, 4], [5.0, '6']]
li2

[[1, 2], [3, 4], [5.0, '6']]

In [225]:
np.array(object = li2)

array([['1', '2'],
       ['3', '4'],
       ['5.0', '6']], dtype='<U32')

In [226]:
df = pd.DataFrame(data = li2)
df

0  1
0  1.0  2
1  3.0  4
2  5.0  6

In [227]:
type(df)

pandas.core.frame.DataFrame

In [228]:
df.shape

(3, 2)

In [229]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [230]:
df.columns

RangeIndex(start=0, stop=2, step=1)

In [231]:
df.dtypes

0    float64
1     object
dtype: object

In [232]:
df.values

array([[1.0, 2],
       [3.0, 4],
       [5.0, '6']], dtype=object)

In [233]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       3 non-null      float64
 1   1       3 non-null      object 
dtypes: float64(1), object(1)
memory usage: 180.0+ bytes


In [235]:
df.index = range(1, 4)
df

0  1
1  1.0  2
2  3.0  4
3  5.0  6

In [236]:
df.columns = ['A', 'B']
df

A  B
1  1.0  2
2  3.0  4
3  5.0  6

In [237]:
pd.DataFrame(data = li2, index = range(1, 4), columns = ['A', 'B'])

A  B
1  1.0  2
2  3.0  4
3  5.0  6

In [238]:
df

A  B
1  1.0  2
2  3.0  4
3  5.0  6

In [239]:
df.iloc[0]

A    1.0
B      2
Name: 1, dtype: object

In [240]:
df.iloc[[0]]

A  B
1  1.0  2

In [246]:
df.iloc[[1, 0, 2]]

A  B
2  3.0  4
1  1.0  2
3  5.0  6

In [241]:
df.iloc[0:2]

A  B
1  1.0  2
2  3.0  4

In [242]:
df.iloc[0:2, :]

A  B
1  1.0  2
2  3.0  4

In [243]:
df.iloc[:, 0]

1    1.0
2    3.0
3    5.0
Name: A, dtype: float64

In [244]:
df.iloc[:, 0:2]

A  B
1  1.0  2
2  3.0  4
3  5.0  6

In [245]:
df.iloc[:, [1, 0]]

B    A
1  2  1.0
2  4  3.0
3  6  5.0

In [247]:
df

A  B
1  1.0  2
2  3.0  4
3  5.0  6

In [249]:
df.loc[1]

A    1.0
B      2
Name: 1, dtype: object

In [250]:
df.loc[[1]]

A  B
1  1.0  2

In [251]:
df.loc[1:2]

A  B
1  1.0  2
2  3.0  4

In [252]:
df.loc[1:2, :]

A  B
1  1.0  2
2  3.0  4

In [253]:
df.loc[:, 'A']

1    1.0
2    3.0
3    5.0
Name: A, dtype: float64

In [254]:
df.loc[:, 'A':'B']

A  B
1  1.0  2
2  3.0  4
3  5.0  6

In [255]:
df.loc[:, ['B', 'A']]

B    A
1  2  1.0
2  4  3.0
3  6  5.0